spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: booking-dev
    password: booking-dev@passwd
  h2:
    console:
      enabled: true
  hibernate:
    ddl-auto: update

  logging:
    level:
      org.springframework: DEBUG

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
